### ISSUE TITLE
Return a boolean instead of void for prepareRevert / prepareUpdate 

### ISSUE THREAD

**Issue by yersan** [wildfly-extras/wildfly-installation-manager-api#4]
There could be a use case where the prepareRevert or prepareUpdate returns no error but the candidate server is not prepared because there are no updates available.

Those methods should return a boolean to indicate when there is no exception, whether the server was prepared.

CC @spyrkob , I remember we talked about this some time ago, so just adding it here.

**Comment by spyrkob** [comment]
@yersan what would be scenario where prepareRevert returns false? 

If the revision doesn't exist in history, an exception is thrown, same if there is an error provisioning the new server, otherwise I don't think there's a situation the candidate server would not be created.
